(define (factorial n)
  (define (fact-iter product counter max-count)
    (if (= max-count counter)
      (* product counter)
      (fact-iter (* product counter) (+ counter 1) max-count)
    )
  )

  (fact-iter 1 1 n)
)